name: Build image

on: [workflow_call]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v3
    - name: lowercase github.repository
      run: |
        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: Build
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest .
    - name: Export
      run: |
        docker save -o /tmp/image.tar ${{ env.IMAGE_NAME }}:latest
    - name: Cache docker image
      run: |
        curl --fail-with-body -X POST -F "file=@/tmp/image.tar" -F "project_id=nikobot" -F "issue_id=1" http://192.168.0.145:25000/dump
    - name: Remove local image
      run: |
        docker image rm ${{ env.IMAGE_NAME }}
