name: Run Tests

on: 
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pylint:
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
    uses: ./.github/workflows/define-pylint.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit
  build:
    needs: [pylint]
    uses: ./.github/workflows/define-build-image.yml
    secrets: inherit
