name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  pylint:
    strategy:
      matrix:
        python-version: ["3.13"]
    uses: ./.github/workflows/define-pylint.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  pytest:
    needs: [pylint]
    strategy:
      matrix:
        python-version: ["3.10", "3.13"]
    uses: ./.github/workflows/define-pytest.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  build:
    needs: [pylint, pytest]
    uses: ./.github/workflows/define-build-image.yml
    secrets: inherit

  push:
    needs: [pylint, pytest, build]
    runs-on: [self-hosted, linux]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: lowercase github.repository
      run: |
        echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
    - name: Download cached docker image
      run: |
        curl --fail-with-body-X GET http://192.168.0.145:25000/attachments/nikobot/1/image.tar -o /tmp/image.tar
    - name: Load image
      run: |
        docker load --input /tmp/image.tar
    - name: Push
      run: |
        docker tag ${{ env.IMAGE_NAME }}:latest ghcr.io/${{ env.IMAGE_NAME }}:dev
        docker push ghcr.io/${{ env.IMAGE_NAME }}:dev
    - name: Remove local image
      if: always()
      run: |
        docker image rm ${{ env.IMAGE_NAME }}
    - name: Remove cached docker image
      if: always()
      run: |
        curl --fail-with-body-X DELETE http://192.168.0.145:25000/attachments/nikobot/1/image.tar
